import type { LocalTemplate } from "./templates";

/**
 * Everyday scenarios that run entirely on local nodes (manual trigger, JSON transform, filter, condition, output).
 * Each one works on the editable sample in its trigger and only saves a result in the run: nothing is sent, bought,
 * booked, approved or cancelled.
 *
 * Expression rules these follow (JSONata semantics, see tests/unit/local-scenarios.test.ts):
 * - A comparison with a missing field is false even for `!=`, so exclusions use `$not(field = value)`.
 * - A one-item sequence collapses to a plain value, so every list is wrapped in `[ … ]`.
 * - When a step's input is a list (after a filter), an object's value that is a path starting with a function runs
 *   once per item, so lists are built in variables first and the object only references them.
 * - Dates are `YYYY-MM-DD` text supplied in the sample; they compare as text and `$toMillis` reads them as UTC.
 * - Amounts are one currency with no tax; `$round(x, 2)` rounds half to even.
 * - Steps are read by node id (`$steps.trigger`), never by label: Arabic flows get translated labels.
 */

const X = [0, 300, 600, 900, 1200];
const J = (v: unknown) => JSON.stringify(v, null, 2);
const lines = (...l: string[]) => l.join("\n");
const EMAIL = String.raw`/^[^@\s]+@[^@\s]+\.[^@\s]+$/`;
const ISO_DATE = String.raw`/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/`;

export const LOCAL_SCENARIOS: LocalTemplate[] = [
  {
    id: "low-stock-list",
    name: "Low Stock List",
    description: "Find the products at or below their reorder level and list them by how many are missing. It only makes a list — nothing is ordered.",
    sample: "Six products, each with the amount on hand and a reorder level.",
    result: "The products to restock, largest shortfall first, or how many products were checked when nothing is low.",
    category: "Operations",
    goal: "data",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Stock count",
            config: {
              samplePayload: J({
                products: [
                  { sku: "FL-101", name: "Paper cups (pack of 50)", onHand: 4, reorderLevel: 10 },
                  { sku: "FL-102", name: "Coffee beans 1 kg", onHand: 12, reorderLevel: 8 },
                  { sku: "FL-103", name: "Oat milk 1 L", onHand: 6, reorderLevel: 6 },
                  { sku: "FL-104", name: "Napkins (pack of 200)", onHand: 0, reorderLevel: 5 },
                  { sku: "FL-105", name: "Sugar sticks (box)", onHand: 30, reorderLevel: 10 },
                  { sku: "FL-106", name: "Tea bags (box of 100)", onHand: 9, reorderLevel: 4 },
                ],
              }),
            },
          },
        },
        { id: "low", type: "data.filter", position: { x: X[1], y: 120 }, data: { label: "At or below reorder level", config: { source: "products", predicate: "$number(onHand) <= $number(reorderLevel)" } } },
        {
          id: "sort",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Sort by shortfall",
            config: {
              expression: lines(
                "(",
                "  $rows := [$.{",
                '    "sku": sku,',
                '    "name": name,',
                '    "onHand": $number(onHand),',
                '    "reorderLevel": $number(reorderLevel),',
                '    "shortBy": $number(reorderLevel) - $number(onHand)',
                "  }];",
                "  {",
                '    "count": $count($rows),',
                '    "items": [$sort($rows, function($a, $b) { $a.shortBy < $b.shortBy or ($a.shortBy = $b.shortBy and $a.sku > $b.sku) })]',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "any", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "Anything to restock?", config: { expression: "count > 0" } } },
        { id: "reorder", type: "output", position: { x: X[4], y: 36 }, data: { label: "Restock list", config: { key: "restock_list", expression: "" } } },
        { id: "stocked", type: "output", position: { x: X[4], y: 216 }, data: { label: "Everything stocked", config: { key: "all_stocked", expression: '{ "checked": $count($steps.trigger.products) }' } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "low", sourceHandle: "out" },
        { id: "e2", source: "low", target: "sort", sourceHandle: "out" },
        { id: "e3", source: "sort", target: "any", sourceHandle: "out" },
        { id: "e4", source: "any", target: "reorder", sourceHandle: "true" },
        { id: "e5", source: "any", target: "stocked", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "invoice-follow-up-list",
    name: "Invoice Follow-up List",
    description: "List unpaid invoices that are past due on the date you choose, with days overdue and the total. It only makes a list — no reminders are sent.",
    sample: "Five invoices in one currency, whether each is paid, and the date to check on.",
    result: "The overdue invoices, oldest first, with days overdue and the total due.",
    category: "Finance",
    goal: "data",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Open invoices",
            config: {
              samplePayload: J({
                asOf: "2026-09-30",
                currency: "USD",
                invoices: [
                  { number: "INV-1041", customer: "Cedar Studio", amount: 1200, dueDate: "2026-09-10", paid: false },
                  { number: "INV-1042", customer: "Nile Bakery", amount: 350.5, dueDate: "2026-09-30", paid: false },
                  { number: "INV-1043", customer: "Blue Harbor", amount: 980, dueDate: "2026-09-01", paid: true },
                  { number: "INV-1044", customer: "Oasis Florist", amount: 415.25, dueDate: "2026-09-22", paid: false },
                  { number: "INV-1045", customer: "Atlas Tutors", amount: 260, dueDate: "2026-10-15", paid: false },
                ],
              }),
            },
          },
        },
        { id: "overdue", type: "data.filter", position: { x: X[1], y: 120 }, data: { label: "Unpaid and past due", config: { source: "invoices", predicate: "$not(paid = true) and dueDate < $steps.trigger.asOf" } } },
        {
          id: "list",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Add days overdue",
            config: {
              expression: lines(
                "(",
                "  $asOf := $steps.trigger.asOf;",
                "  $rows := [$sort($, function($a, $b) { $a.dueDate > $b.dueDate or ($a.dueDate = $b.dueDate and $a.number > $b.number) }).{",
                '    "number": number,',
                '    "customer": customer,',
                '    "amount": $number(amount),',
                '    "dueDate": dueDate,',
                '    "daysOverdue": $round(($toMillis($asOf) - $toMillis(dueDate)) / 86400000)',
                "  }];",
                "  {",
                '    "asOf": $asOf,',
                '    "currency": $steps.trigger.currency,',
                '    "count": $count($rows),',
                '    "totalDue": $round($sum([$rows.amount]), 2),',
                '    "invoices": $rows',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "any", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "Anything overdue?", config: { expression: "count > 0" } } },
        { id: "follow", type: "output", position: { x: X[4], y: 36 }, data: { label: "Follow-up list", config: { key: "follow_up", expression: "" } } },
        { id: "clear", type: "output", position: { x: X[4], y: 216 }, data: { label: "Nothing overdue", config: { key: "nothing_overdue", expression: '{ "asOf": asOf, "count": 0 }' } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "overdue", sourceHandle: "out" },
        { id: "e2", source: "overdue", target: "list", sourceHandle: "out" },
        { id: "e3", source: "list", target: "any", sourceHandle: "out" },
        { id: "e4", source: "any", target: "follow", sourceHandle: "true" },
        { id: "e5", source: "any", target: "clear", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "quote-calculator",
    name: "Quote Calculator",
    description: "Work out the line totals, subtotal, an optional discount and the final total for a quote in one currency. Tax isn't added, and nothing is sent to the customer.",
    sample: "Three quote lines with quantity and unit price, and a 10% discount.",
    result: "Each line total, the subtotal, the discount and the final total, rounded to two decimals.",
    category: "Sales",
    goal: "sales",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Quote request",
            config: {
              samplePayload: J({
                customer: "Nile Bakery",
                currency: "USD",
                discountPercent: 10,
                lines: [
                  { item: "Logo design", qty: 1, unitPrice: 250 },
                  { item: "Menu printing", qty: 200, unitPrice: 0.35 },
                  { item: "Window sticker", qty: 3, unitPrice: 14.99 },
                ],
              }),
            },
          },
        },
        {
          id: "calc",
          type: "transform.json",
          position: { x: X[1], y: 120 },
          data: {
            label: "Work out the totals",
            config: {
              expression: lines(
                "(",
                "  $lines := [lines.{",
                '    "item": item,',
                '    "qty": $number(qty),',
                '    "unitPrice": $number(unitPrice),',
                '    "lineTotal": $round($number(qty) * $number(unitPrice), 2)',
                "  }];",
                "  $pct := $exists(discountPercent) ? $number(discountPercent) : 0;",
                "  $subtotal := $round($sum([$lines.lineTotal]), 2);",
                "  $discount := $round($subtotal * $pct / 100, 2);",
                "  {",
                '    "customer": customer,',
                '    "currency": currency,',
                '    "lines": $lines,',
                '    "lineCount": $count($lines),',
                '    "subtotal": $subtotal,',
                '    "discountPercent": $pct,',
                '    "discount": $discount,',
                '    "total": $round($subtotal - $discount, 2)',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "valid", type: "logic.condition", position: { x: X[2], y: 120 }, data: { label: "Lines and a 0–100% discount?", config: { expression: 'lineCount > 0 and discountPercent >= 0 and discountPercent <= 100 and $count($steps.trigger.lines[$type(qty) = "number" and qty > 0 and $type(unitPrice) = "number" and unitPrice >= 0]) = lineCount' } } },
        { id: "quote", type: "output", position: { x: X[3], y: 36 }, data: { label: "Quote totals", config: { key: "quote", expression: "" } } },
        { id: "fix", type: "output", position: { x: X[3], y: 216 }, data: { label: "Needs a fix", config: { key: "needs_fix", expression: '{ "lineCount": lineCount, "discountPercent": discountPercent }' } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "calc", sourceHandle: "out" },
        { id: "e2", source: "calc", target: "valid", sourceHandle: "out" },
        { id: "e3", source: "valid", target: "quote", sourceHandle: "true" },
        { id: "e4", source: "valid", target: "fix", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "order-packing-list",
    name: "Order Packing List",
    description: "Pick the paid orders due to ship by your packing date and total how many of each item to pack. It only makes a list — nothing is shipped or charged.",
    sample: "Five orders with a status, a ship-by date and items, and the packing date.",
    result: "The orders to pack and one pick list with the total quantity of each item.",
    category: "Operations",
    goal: "data",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Today's orders",
            config: {
              samplePayload: J({
                packDate: "2026-10-01",
                orders: [
                  { orderId: "SO-2201", status: "paid", shipBy: "2026-10-01", items: [{ sku: "MUG-01", name: "Ceramic mug", qty: 2 }, { sku: "TEA-10", name: "Mint tea tin", qty: 1 }] },
                  { orderId: "SO-2202", status: "paid", shipBy: "2026-09-30", items: [{ sku: "MUG-01", name: "Ceramic mug", qty: 1 }] },
                  { orderId: "SO-2203", status: "pending", shipBy: "2026-10-01", items: [{ sku: "TEA-10", name: "Mint tea tin", qty: 4 }] },
                  { orderId: "SO-2204", status: "paid", shipBy: "2026-10-03", items: [{ sku: "BAG-05", name: "Tote bag", qty: 1 }] },
                  { orderId: "SO-2205", status: "cancelled", shipBy: "2026-09-29", items: [{ sku: "BAG-05", name: "Tote bag", qty: 2 }] },
                ],
              }),
            },
          },
        },
        { id: "ready", type: "data.filter", position: { x: X[1], y: 120 }, data: { label: "Paid and due to ship", config: { source: "orders", predicate: 'status = "paid" and shipBy <= $steps.trigger.packDate' } } },
        {
          id: "pick",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Total each item",
            config: {
              expression: lines(
                "(",
                "  $orders := [$];",
                "  $items := [$orders.items];",
                "  $skus := $sort([$distinct($items.sku)]);",
                "  $pickList := [$skus.(",
                "    $sku := $;",
                "    $same := $items[sku = $sku];",
                '    { "sku": $sku, "name": $same[0].name, "qty": $sum([$same.$number(qty)]) }',
                "  )];",
                "  {",
                '    "packDate": $steps.trigger.packDate,',
                '    "orderCount": $count($orders),',
                '    "orders": [$orders.orderId],',
                '    "pickList": $pickList',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "any", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "Anything to pack?", config: { expression: "orderCount > 0" } } },
        { id: "list", type: "output", position: { x: X[4], y: 36 }, data: { label: "Packing list", config: { key: "packing_list", expression: "" } } },
        { id: "none", type: "output", position: { x: X[4], y: 216 }, data: { label: "Nothing to pack", config: { key: "nothing_to_pack", expression: '{ "packDate": packDate, "orderCount": 0 }' } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "ready", sourceHandle: "out" },
        { id: "e2", source: "ready", target: "pick", sourceHandle: "out" },
        { id: "e3", source: "pick", target: "any", sourceHandle: "out" },
        { id: "e4", source: "any", target: "list", sourceHandle: "true" },
        { id: "e5", source: "any", target: "none", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "expense-category-summary",
    name: "Expense Category Summary",
    description: "Total your expenses by category for the dates you choose, in one currency. It only adds up what you enter.",
    sample: "Seven expenses in one currency and a date range; two fall outside it.",
    result: "The total and count for each category, largest first, and the overall total.",
    category: "Finance",
    goal: "data",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Expenses",
            config: {
              samplePayload: J({
                currency: "USD",
                from: "2026-09-01",
                to: "2026-09-30",
                expenses: [
                  { date: "2026-08-31", category: "Travel", amount: 60, note: "Taxi" },
                  { date: "2026-09-01", category: "Travel", amount: 42.5, note: "Train ticket" },
                  { date: "2026-09-12", category: "Software", amount: 19.99, note: "Design app" },
                  { date: "2026-09-18", category: "Meals", amount: 23.4, note: "Team lunch" },
                  { date: "2026-09-25", category: "Travel", amount: 18.25, note: "Parking" },
                  { date: "2026-09-30", category: "Software", amount: 9.99, note: "Storage plan" },
                  { date: "2026-10-01", category: "Meals", amount: 31, note: "Client coffee" },
                ],
              }),
            },
          },
        },
        { id: "range", type: "data.filter", position: { x: X[1], y: 120 }, data: { label: "Inside the date range", config: { source: "expenses", predicate: "date >= $steps.trigger.from and date <= $steps.trigger.to" } } },
        {
          id: "totals",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Total per category",
            config: {
              expression: lines(
                "(",
                "  $rows := [$];",
                "  $byCategory := [[$distinct($rows.category)].(",
                "    $name := $;",
                "    $same := $rows[category = $name];",
                '    { "category": $name, "count": $count($same), "total": $round($sum([$same.$number(amount)]), 2) }',
                "  )];",
                "  {",
                '    "from": $steps.trigger.from,',
                '    "to": $steps.trigger.to,',
                '    "currency": $steps.trigger.currency,',
                '    "count": $count($rows),',
                '    "total": $round($sum([$rows.$number(amount)]), 2),',
                '    "byCategory": [$sort($byCategory, function($a, $b) { $a.total < $b.total or ($a.total = $b.total and $a.category > $b.category) })]',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "any", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "Any expenses in range?", config: { expression: "count > 0" } } },
        { id: "summary", type: "output", position: { x: X[4], y: 36 }, data: { label: "Category totals", config: { key: "expense_summary", expression: "" } } },
        { id: "empty", type: "output", position: { x: X[4], y: 216 }, data: { label: "No expenses in range", config: { key: "no_expenses", expression: '{ "from": from, "to": to, "count": 0 }' } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "range", sourceHandle: "out" },
        { id: "e2", source: "range", target: "totals", sourceHandle: "out" },
        { id: "e3", source: "totals", target: "any", sourceHandle: "out" },
        { id: "e4", source: "any", target: "summary", sourceHandle: "true" },
        { id: "e5", source: "any", target: "empty", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "subscription-review",
    name: "Subscription Review",
    description: "See which subscriptions renew in the dates you choose and what they all cost per year. It only makes a list — nothing is cancelled or changed.",
    sample: "Five personal subscriptions, monthly or yearly, in one currency, and a date range.",
    result: "The renewals in the range, soonest first, and the yearly total for all subscriptions.",
    category: "Personal",
    goal: "data",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "My subscriptions",
            config: {
              samplePayload: J({
                currency: "USD",
                from: "2026-10-01",
                to: "2026-10-31",
                subscriptions: [
                  { name: "Music streaming", amount: 10.99, cycle: "monthly", nextRenewal: "2026-10-05" },
                  { name: "Cloud storage", amount: 99, cycle: "yearly", nextRenewal: "2026-10-31" },
                  { name: "Video streaming", amount: 15.49, cycle: "monthly", nextRenewal: "2026-11-02" },
                  { name: "Language app", amount: 59.99, cycle: "yearly", nextRenewal: "2027-03-14" },
                  { name: "News site", amount: 4.99, cycle: "monthly", nextRenewal: "2026-10-18" },
                ],
              }),
            },
          },
        },
        {
          id: "cost",
          type: "transform.json",
          position: { x: X[1], y: 120 },
          data: {
            label: "Yearly cost of each",
            config: {
              expression: lines(
                "(",
                "  $subs := [subscriptions.{",
                '    "name": name,',
                '    "amount": $number(amount),',
                '    "cycle": cycle,',
                '    "nextRenewal": nextRenewal,',
                '    "yearlyCost": cycle = "yearly" ? $round($number(amount), 2) : cycle = "monthly" ? $round($number(amount) * 12, 2) : null',
                "  }];",
                "  {",
                '    "yearlyTotal": $round($sum([$subs[$type(yearlyCost) = "number"].yearlyCost]), 2),',
                '    "unknownCycle": [$subs[$type(yearlyCost) != "number"].name],',
                '    "subscriptions": $subs',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "renewing", type: "data.filter", position: { x: X[2], y: 120 }, data: { label: "Renews in the date range", config: { source: "subscriptions", predicate: "nextRenewal >= $steps.trigger.from and nextRenewal <= $steps.trigger.to" } } },
        {
          id: "review",
          type: "transform.json",
          position: { x: X[3], y: 120 },
          data: {
            label: "Renewal list",
            config: {
              expression: lines(
                "{",
                '  "from": $steps.trigger.from,',
                '  "to": $steps.trigger.to,',
                '  "currency": $steps.trigger.currency,',
                '  "yearlyTotal": $steps.cost.yearlyTotal,',
                '  "unknownCycle": $steps.cost.unknownCycle,',
                '  "renewingCount": $count($),',
                '  "renewing": [$sort($, function($a, $b) { $a.nextRenewal > $b.nextRenewal or ($a.nextRenewal = $b.nextRenewal and $a.name > $b.name) })]',
                "}",
              ),
            },
          },
        },
        { id: "result", type: "output", position: { x: X[4], y: 120 }, data: { label: "Subscriptions to review", config: { key: "subscription_review", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "cost", sourceHandle: "out" },
        { id: "e2", source: "cost", target: "renewing", sourceHandle: "out" },
        { id: "e3", source: "renewing", target: "review", sourceHandle: "out" },
        { id: "e4", source: "review", target: "result", sourceHandle: "out" },
      ],
    },
  },
  {
    id: "weekly-task-plan",
    name: "Weekly Task Plan",
    description: "Put open tasks in due-date and priority order, including overdue tasks. Keep that order: when a task exceeds your hours, it and all later tasks wait. Your calendar isn't changed.",
    sample: "Six tasks with a due date, hours and priority, one week, and 10 available hours.",
    result: "The tasks that fit before the first overflow, in order, and that task and all later tasks to review.",
    category: "Personal",
    goal: "engineering",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "My tasks",
            config: {
              samplePayload: J({
                weekStart: "2026-10-05",
                weekEnd: "2026-10-11",
                hoursAvailable: 10,
                tasks: [
                  { title: "Send project update", due: "2026-10-02", hours: 1, priority: 1, done: false },
                  { title: "Prepare workshop slides", due: "2026-10-07", hours: 4, priority: 1, done: false },
                  { title: "Review budget draft", due: "2026-10-07", hours: 2, priority: 2, done: false },
                  { title: "Write blog post", due: "2026-10-10", hours: 5, priority: 3, done: false },
                  { title: "Plan team offsite", due: "2026-10-20", hours: 3, priority: 2, done: false },
                  { title: "Update CV", due: "2026-10-06", hours: 2, priority: 2, done: true },
                ],
              }),
            },
          },
        },
        { id: "open", type: "data.filter", position: { x: X[1], y: 120 }, data: { label: "Open and due by week end", config: { source: "tasks", predicate: "$not(done = true) and due <= $steps.trigger.weekEnd" } } },
        {
          id: "plan",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Fit tasks into your hours",
            config: {
              expression: lines(
                "(",
                "  $cap := $number($steps.trigger.hoursAvailable);",
                "  $start := $steps.trigger.weekStart;",
                "  $sorted := [$sort($, function($a, $b) { $a.due > $b.due or ($a.due = $b.due and ($a.priority > $b.priority or ($a.priority = $b.priority and $a.title > $b.title))) })];",
                "  $plan := [$map($sorted, function($t, $i) {",
                "    {",
                '      "title": $t.title,',
                '      "due": $t.due,',
                '      "hours": $number($t.hours),',
                '      "overdue": $t.due < $start,',
                '      "fits": $sum([$sorted[[0..$i]].$number(hours)]) <= $cap',
                "    }",
                "  })];",
                "  {",
                '    "weekStart": $start,',
                '    "weekEnd": $steps.trigger.weekEnd,',
                '    "hoursAvailable": $cap,',
                '    "hoursPlanned": $round($sum([$plan[fits].hours]), 2),',
                '    "thisWeek": [$plan[fits]],',
                '    "later": [$plan[$not(fits)]]',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "over", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "More than your hours?", config: { expression: "$count(later) > 0" } } },
        { id: "overflow", type: "output", position: { x: X[4], y: 36 }, data: { label: "Plan with tasks left over", config: { key: "plan_with_overflow", expression: "" } } },
        { id: "fits", type: "output", position: { x: X[4], y: 216 }, data: { label: "Plan fits your week", config: { key: "weekly_plan", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "open", sourceHandle: "out" },
        { id: "e2", source: "open", target: "plan", sourceHandle: "out" },
        { id: "e3", source: "plan", target: "over", sourceHandle: "out" },
        { id: "e4", source: "over", target: "overflow", sourceHandle: "true" },
        { id: "e5", source: "over", target: "fits", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "event-attendee-summary",
    name: "Event Attendee Summary",
    description: "Count who is registered for an event, once per email, by ticket type and check-in, and compare it with the capacity. No messages are sent to attendees.",
    sample: "Six sign-ups for one event, including a cancellation and a repeated email.",
    result: "Registered, checked-in and cancelled counts, the count per ticket type, and seats left.",
    category: "Operations",
    goal: "data",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Sign-ups",
            config: {
              samplePayload: J({
                event: "Community meetup",
                capacity: 40,
                attendees: [
                  { name: "Mona Adel", email: "mona@example.com", ticket: "standard", status: "registered", checkedIn: true },
                  { name: "Omar Said", email: "omar@example.com", ticket: "vip", status: "registered", checkedIn: false },
                  { name: "Mona Adel", email: " MONA@example.com ", ticket: "standard", status: "registered", checkedIn: false },
                  { name: "Lina Haddad", email: "lina@example.com", ticket: "standard", status: "cancelled", checkedIn: false },
                  { name: "Karim Nabil", email: "karim@example.com", ticket: "standard", status: "registered", checkedIn: true },
                  { name: "Sara Ali", email: "sara@example.com", ticket: "vip", status: "registered", checkedIn: false },
                ],
              }),
            },
          },
        },
        {
          id: "count",
          type: "transform.json",
          position: { x: X[1], y: 120 },
          data: {
            label: "Count registrations",
            config: {
              expression: lines(
                "(",
                '  $key := function($a) { $exists($a.email) ? $lowercase($trim($a.email)) : "" };',
                '  $active := [attendees[$not(status = "cancelled")]];',
                '  $identified := [$active[$key($) != ""]];',
                '  $unknown := [$active[$key($) = ""]];',
                '  $unique := [$append([[$distinct($identified.$key($))].( $k := $; $same := [$identified[$key($) = $k]]; $merge([$same[0], {"checkedIn": $count($same[checkedIn = true]) > 0}]) )], $unknown)];',
                "  {",
                '    "event": event,',
                '    "capacity": $number(capacity),',
                '    "registered": $count($unique),',
                '    "duplicatesIgnored": $count($active) - $count($unique),',
                '    "cancelled": $count(attendees[status = "cancelled"]),',
                '    "checkedIn": $count($unique[checkedIn = true]),',
                '    "byTicket": [$sort([$distinct($unique.ticket)]).( $t := $; { "ticket": $t, "count": $count($unique[ticket = $t]) } )],',
                '    "seatsLeft": $number(capacity) - $count($unique)',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "full", type: "logic.condition", position: { x: X[2], y: 120 }, data: { label: "Over capacity?", config: { expression: "seatsLeft < 0" } } },
        { id: "over", type: "output", position: { x: X[3], y: 36 }, data: { label: "Over capacity", config: { key: "over_capacity", expression: "" } } },
        { id: "summary", type: "output", position: { x: X[3], y: 216 }, data: { label: "Attendee summary", config: { key: "attendee_summary", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "count", sourceHandle: "out" },
        { id: "e2", source: "count", target: "full", sourceHandle: "out" },
        { id: "e3", source: "full", target: "over", sourceHandle: "true" },
        { id: "e4", source: "full", target: "summary", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "registration-check",
    name: "Registration Check",
    description: "Check one sign-up for a name, an email that looks valid and a course, and that it arrived within the registration dates you set. Nothing is confirmed or sent.",
    sample: "One registration sent on the last day the registration window is open.",
    result: "The tidied registration and a list of problems, which is empty when it is complete.",
    category: "Operations",
    goal: "support",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "New registration",
            config: {
              samplePayload: J({
                window: { opens: "2026-10-01", closes: "2026-10-15" },
                registration: { name: "Yara Mansour", email: "Yara@Example.com", course: "Intro to budgeting", submittedOn: "2026-10-15" },
              }),
            },
          },
        },
        {
          id: "check",
          type: "transform.json",
          position: { x: X[1], y: 120 },
          data: {
            label: "Check the details",
            config: {
              expression: lines(
                "(",
                "  $r := registration;",
                '  $blank := function($v) { $not($exists($v)) or $trim($string($v)) = "" };',
                '  $email := $exists($r.email) ? $lowercase($trim($r.email)) : "";',
                `  $dateOk := function($v) { $type($v) = "string" and $contains($v, ${ISO_DATE}) ? ( $y := $number($substring($v,0,4)); $m := $number($substring($v,5,2)); $d := $number($substring($v,8,2)); $days := $m = 2 ? (($y % 4 = 0 and ($y % 100 != 0 or $y % 400 = 0)) ? 29 : 28) : ($m in [4,6,9,11] ? 30 : 31); $y > 0 and $d <= $days ) : false };`,
                "  $windowOk := $dateOk(window.opens) and $dateOk(window.closes) and window.opens <= window.closes;",
                "  $problems := [",
                '    $blank($r.name) ? "missing_name",',
                `    $not($contains($email, ${EMAIL})) ? "invalid_email",`,
                '    $blank($r.course) ? "missing_course",',
                '    $not($windowOk) ? "invalid_window",',
                '    $blank($r.submittedOn) ? "missing_date" : $not($dateOk($r.submittedOn)) ? "invalid_date" : ($windowOk and ($r.submittedOn < window.opens or $r.submittedOn > window.closes)) ? "outside_window"',
                "  ];",
                "  {",
                '    "name": $trim($r.name),',
                '    "email": $email,',
                '    "course": $r.course,',
                '    "submittedOn": $r.submittedOn,',
                '    "opens": window.opens,',
                '    "closes": window.closes,',
                '    "problems": $problems,',
                '    "complete": $count($problems) = 0',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "ok", type: "logic.condition", position: { x: X[2], y: 120 }, data: { label: "Complete and on time?", config: { expression: "complete" } } },
        { id: "complete", type: "output", position: { x: X[3], y: 36 }, data: { label: "Complete", config: { key: "complete_registration", expression: "" } } },
        { id: "follow", type: "output", position: { x: X[3], y: 216 }, data: { label: "Needs follow-up", config: { key: "needs_follow_up", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "check", sourceHandle: "out" },
        { id: "e2", source: "check", target: "ok", sourceHandle: "out" },
        { id: "e3", source: "ok", target: "complete", sourceHandle: "true" },
        { id: "e4", source: "ok", target: "follow", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "contact-list-cleanup",
    name: "Contact List Cleanup",
    description: "Tidy names and emails, keep one contact per email address, and list the contacts that need a valid email. Nothing is sent to anyone.",
    sample: "Six contacts with extra spaces, repeated emails in different letter case, and two unusable emails.",
    result: "One contact per email, sorted by email, with counts and the names that still need an email.",
    category: "Sales",
    goal: "sales",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Contact list",
            config: {
              samplePayload: J({
                contacts: [
                  { name: "  Hana Youssef ", email: "Hana@Example.com", company: "Cedar Studio" },
                  { name: "Hana Youssef", email: "hana@example.com ", company: "Cedar Studio" },
                  { name: "Tarek Fawzi", email: "tarek@example.com", company: "Atlas Tutors" },
                  { name: "Rania Samir", email: "", company: "Oasis Florist" },
                  { name: "Adam Kareem", email: "adam(at)example.com", company: "Blue Harbor" },
                  { name: "Tarek Fawzi", email: "TAREK@example.com", company: "Atlas Tutors LLC" },
                ],
              }),
            },
          },
        },
        {
          id: "clean",
          type: "transform.json",
          position: { x: X[1], y: 120 },
          data: {
            label: "Tidy and remove duplicates",
            config: {
              expression: lines(
                "(",
                `  $valid := function($c) { $contains($c.email, ${EMAIL}) };`,
                "  $clean := [contacts.{",
                '    "name": $trim(name),',
                '    "email": $exists(email) ? $lowercase($trim(email)) : "",',
                '    "company": $trim(company)',
                "  }];",
                "  $good := [$clean[$valid($)]];",
                "  $unique := [[$distinct($good.email)].( $e := $; $good[email = $e][0] )];",
                "  {",
                '    "received": $count($clean),',
                '    "kept": $count($unique),',
                '    "duplicatesRemoved": $count($good) - $count($unique),',
                '    "needsEmail": [$clean[$not($valid($))].name],',
                '    "contacts": [$sort($unique, function($a, $b) { $a.email > $b.email })]',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "result", type: "output", position: { x: X[2], y: 120 }, data: { label: "Clean contact list", config: { key: "clean_contacts", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "clean", sourceHandle: "out" },
        { id: "e2", source: "clean", target: "result", sourceHandle: "out" },
      ],
    },
  },
  {
    id: "support-backlog-summary",
    name: "Support Backlog Summary",
    description: "Count open tickets by priority and list the ones with no update for a set number of days, as of the date you choose. No replies are sent.",
    sample: "Five tickets with a status, priority and last update, a check date and a 7-day limit.",
    result: "Open tickets per priority and the ones waiting too long, longest first.",
    category: "Support",
    goal: "support",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Ticket list",
            config: {
              samplePayload: J({
                asOf: "2026-09-30",
                staleAfterDays: 7,
                tickets: [
                  { id: 5101, subject: "Can't reset password", status: "open", priority: "high", lastUpdate: "2026-09-29" },
                  { id: 5102, subject: "Invoice shows the wrong address", status: "pending", priority: "normal", lastUpdate: "2026-09-23" },
                  { id: 5103, subject: "Export to spreadsheet fails", status: "open", priority: "high", lastUpdate: "2026-09-15" },
                  { id: 5104, subject: "Question about plans", status: "closed", priority: "low", lastUpdate: "2026-09-10" },
                  { id: 5105, subject: "Dark mode request", status: "open", priority: "low", lastUpdate: "2026-09-24" },
                ],
              }),
            },
          },
        },
        { id: "open", type: "data.filter", position: { x: X[1], y: 120 }, data: { label: "Not closed", config: { source: "tickets", predicate: '$not(status = "closed")' } } },
        {
          id: "summary",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Count and find waiting tickets",
            config: {
              expression: lines(
                "(",
                "  $asOf := $steps.trigger.asOf;",
                "  $limit := $number($steps.trigger.staleAfterDays);",
                "  $open := [$.{",
                '    "id": id,',
                '    "subject": subject,',
                '    "status": status,',
                '    "priority": priority,',
                '    "lastUpdate": lastUpdate,',
                '    "daysSinceUpdate": $round(($toMillis($asOf) - $toMillis(lastUpdate)) / 86400000)',
                "  }];",
                "  $stale := [$open[daysSinceUpdate >= $limit]];",
                "  {",
                '    "asOf": $asOf,',
                '    "open": $count($open),',
                '    "byPriority": {',
                '      "high": $count($open[priority = "high"]),',
                '      "normal": $count($open[priority = "normal"]),',
                '      "low": $count($open[priority = "low"]),',
                '      "other": $count($open[$not(priority in ["high", "normal", "low"])])',
                "    },",
                '    "staleCount": $count($stale),',
                '    "stale": [$sort($stale, function($a, $b) { $a.daysSinceUpdate < $b.daysSinceUpdate or ($a.daysSinceUpdate = $b.daysSinceUpdate and $a.id > $b.id) })]',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "any", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "Anything waiting too long?", config: { expression: "staleCount > 0" } } },
        { id: "attention", type: "output", position: { x: X[4], y: 36 }, data: { label: "Needs attention", config: { key: "stale_backlog", expression: "" } } },
        { id: "fresh", type: "output", position: { x: X[4], y: 216 }, data: { label: "Backlog is up to date", config: { key: "backlog_summary", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "open", sourceHandle: "out" },
        { id: "e2", source: "open", target: "summary", sourceHandle: "out" },
        { id: "e3", source: "summary", target: "any", sourceHandle: "out" },
        { id: "e4", source: "any", target: "attention", sourceHandle: "true" },
        { id: "e5", source: "any", target: "fresh", sourceHandle: "false" },
      ],
    },
  },
  {
    id: "survey-score-summary",
    name: "Survey Score Summary",
    description: "Summarise 1–5 survey scores for the dates you choose: the average, the share of 4s and 5s, the count per score and the low scores to read. Nothing is sent to respondents.",
    sample: "Six survey answers with a 1–5 score and a comment; one falls outside the dates.",
    result: "The average, the share satisfied, the count per score and the answers that scored 2 or less.",
    category: "Support",
    goal: "support",
    graph: {
      nodes: [
        {
          id: "trigger",
          type: "trigger.manual",
          position: { x: X[0], y: 120 },
          data: {
            label: "Survey answers",
            config: {
              samplePayload: J({
                from: "2026-09-01",
                to: "2026-09-30",
                responses: [
                  { respondent: "R-01", date: "2026-09-02", score: 5, comment: "Quick and friendly" },
                  { respondent: "R-02", date: "2026-09-09", score: 4, comment: "" },
                  { respondent: "R-03", date: "2026-09-14", score: 2, comment: "Waited too long" },
                  { respondent: "R-04", date: "2026-09-20", score: 5, comment: "" },
                  { respondent: "R-05", date: "2026-09-30", score: 3, comment: "Fine" },
                  { respondent: "R-06", date: "2026-10-01", score: 1, comment: "Late answer" },
                ],
              }),
            },
          },
        },
        {
          id: "valid",
          type: "data.filter",
          position: { x: X[1], y: 120 },
          data: {
            label: "In range with a 1–5 score",
            config: { source: "responses", predicate: 'date >= $steps.trigger.from and date <= $steps.trigger.to and $type(score) = "number" and score >= 1 and score <= 5 and $floor(score) = score' },
          },
        },
        {
          id: "summary",
          type: "transform.json",
          position: { x: X[2], y: 120 },
          data: {
            label: "Average and spread",
            config: {
              expression: lines(
                "(",
                "  $r := [$];",
                "  $n := $count($r);",
                "  $scale := [1, 2, 3, 4, 5];",
                '  $byScore := [$scale.( $s := $; { "score": $s, "count": $count($r[score = $s]) } )];',
                "  {",
                '    "from": $steps.trigger.from,',
                '    "to": $steps.trigger.to,',
                '    "counted": $n,',
                '    "notCounted": $count($steps.trigger.responses) - $n,',
                '    "average": $n > 0 ? $round($average($r.score), 2) : null,',
                '    "satisfiedPercent": $n > 0 ? $round(100 * $count($r[score >= 4]) / $n, 1) : null,',
                '    "byScore": $byScore,',
                '    "lowScores": [$r[score <= 2].{ "respondent": respondent, "date": date, "score": score, "comment": comment }]',
                "  }",
                ")",
              ),
            },
          },
        },
        { id: "low", type: "logic.condition", position: { x: X[3], y: 120 }, data: { label: "Any scores of 2 or less?", config: { expression: "$count(lowScores) > 0" } } },
        { id: "review", type: "output", position: { x: X[4], y: 36 }, data: { label: "Summary with low scores", config: { key: "survey_low_scores", expression: "" } } },
        { id: "scores", type: "output", position: { x: X[4], y: 216 }, data: { label: "Score summary", config: { key: "survey_summary", expression: "" } } },
      ],
      edges: [
        { id: "e1", source: "trigger", target: "valid", sourceHandle: "out" },
        { id: "e2", source: "valid", target: "summary", sourceHandle: "out" },
        { id: "e3", source: "summary", target: "low", sourceHandle: "out" },
        { id: "e4", source: "low", target: "review", sourceHandle: "true" },
        { id: "e5", source: "low", target: "scores", sourceHandle: "false" },
      ],
    },
  },
];
