import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
const number = process.argv[2];
if (!/^\d+$/.test(number ?? '')) throw new Error('Checkpoint number required');
const ref = `refs/checkpoints/design-v2-closeout-${number}`;
const index = path.join(mkdtempSync(path.join(tmpdir(), 'flowline-keyboard-index-')), 'index');
const git = (...args) => execFileSync('git', args, { encoding: 'utf8', env: { ...process.env, GIT_INDEX_FILE: index }, stdio: ['pipe', 'pipe', 'pipe'] }).trim();
git('read-tree', 'HEAD');
git('add', '-A');
const tree = git('write-tree');
const parent = git('rev-parse', Number(number) === 13 ? 'refs/checkpoints/design-v2-closeout-12' : `refs/checkpoints/design-v2-closeout-${Number(number)-1}`);
const commit = git('commit-tree', tree, '-p', parent, '-m', `design-v2 exhaustive keyboard candidate ${number}`);
git('update-ref', ref, commit, '0000000000000000000000000000000000000000');
const inputs = Object.fromEntries(['src','e2e','tests','scripts','worker','drizzle','package.json','pnpm-lock.yaml','playwright.config.ts','next.config.ts'].map(p=>[p,git('rev-parse',`${commit}:${p}`)]));
writeFileSync(`artifacts/design-v2/gate/final-keyboard/checkpoint-${number}.json`, JSON.stringify({ ref, commit, tree, inputs }, null, 2));
console.log(commit);
