import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';

const root = 'artifacts/phase-1/codex-review';
const email = JSON.parse(readFileSync(`${root}/journey-events.json`, 'utf8')).email;
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ baseURL: 'http://localhost:3100', viewport: { width: 1440, height: 900 } });
const page = await context.newPage();
const events = [];
page.on('console', m => { if (m.type() === 'error') events.push(m.text().slice(0, 500)); });
const pos = n => n.evaluate(e => { const m = e.style.transform.match(/translate\(([-\d.]+)px,\s*([-\d.]+)px/); return { x: Number(m?.[1]), y: Number(m?.[2]) }; });
try {
  await page.goto('/sign-in');
  await page.getByLabel('Email').fill(email); await page.getByLabel('Password').fill('Codex-Test-Pass-1');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.waitForURL(/\/flows$/);
  await page.getByRole('link', { name: /Codex Offline Draft/ }).first().click();
  await page.locator('.react-flow__node[data-id="normalise"]').waitFor();
  const node = page.locator('.react-flow__node[data-id="normalise"]');
  await node.click();
  const p0 = await pos(node);
  await page.keyboard.press('ArrowRight');
  const p1 = await pos(node);
  await page.keyboard.press('Shift+ArrowDown');
  const p2 = await pos(node);
  console.log('NUDGE', JSON.stringify({ p0, p1, p2, right: p1.x-p0.x, shiftDown: p2.y-p1.y }));
  await page.screenshot({ path: `${root}/screenshots/nudge-isolated.png` });
  await page.getByTestId('save-status').getByText('Saved', { exact: true }).waitFor({ timeout: 15000 });
  await page.reload(); await node.waitFor();
  console.log('NUDGE_AFTER_RELOAD', JSON.stringify(await pos(node)));
  await node.click();
  await page.getByTestId('node-drawer').getByLabel('Name').fill('QA Transform');
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape');
  await page.getByTestId('save-status').getByText('Saved', { exact: true }).waitFor({ timeout: 15000 });
  await page.reload(); await node.waitFor(); await node.click();
  console.log('DRAWER_PERSISTENCE', await page.getByTestId('node-drawer').getByLabel('Name').inputValue());
  await page.screenshot({ path: `${root}/screenshots/drawer-persisted.png` });
  const vp0 = await page.locator('.react-flow__viewport').getAttribute('style');
  await page.getByRole('button', { name: 'Zoom in' }).click();
  const vp1 = await page.locator('.react-flow__viewport').getAttribute('style');
  await page.keyboard.press('Control+0');
  await page.waitForTimeout(400);
  const vp2 = await page.locator('.react-flow__viewport').getAttribute('style');
  console.log('ZOOM', JSON.stringify({ vp0, vp1, vp2 }));
  console.log('EVENTS', JSON.stringify(events));
} finally { await browser.close(); }
