import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
const out = path.resolve('artifacts/beta-execution/20260930T122429Z');
const prior = JSON.parse(readFileSync(path.join(out, 'checkpoint-22.json'), 'utf8'));
const indexPath = execFileSync('git', ['rev-parse', '--git-path', 'index'], {encoding:'utf8'}).trim();
const hash = () => createHash('sha256').update(readFileSync(indexPath)).digest('hex');
const before = hash();
const privateDir = path.resolve('artifacts/beta-execution/.profile/local-staging-20260930');
mkdirSync(privateDir, {recursive:true});
const index = path.join(mkdtempSync(path.join(privateDir, 'cp23-index-')), 'index');
const git = (...args) => execFileSync('git', args, {encoding:'utf8', env:{...process.env,GIT_INDEX_FILE:index},stdio:['ignore','pipe','pipe']}).trim();
if (git('branch','--show-current') !== 'design-v2') throw new Error('Wrong branch');
if (git('rev-parse','refs/checkpoints/design-v2-closeout-22') !== prior.commit) throw new Error('Prior checkpoint changed');
git('read-tree','HEAD');
git('add','--',...Object.keys(prior.inputs));
const tree = git('write-tree');
const inputs = Object.fromEntries(Object.keys(prior.inputs).map(p=>[p,git('rev-parse',tree+':'+p)]));
const changed = Object.keys(inputs).filter(p=>inputs[p]!==prior.inputs[p]);
if (changed.some(p=>!['src','tests','scripts'].includes(p))) throw new Error('Unexpected execution input drift');
const ref = 'refs/checkpoints/design-v2-closeout-23';
const commit = git('commit-tree',tree,'-p',prior.commit,'-m','design-v2 beta: drain stale synthetic recovery fixtures before exact-call observation');
git('update-ref',ref,commit,'0000000000000000000000000000000000000000');
if (hash()!==before) throw new Error('Real index changed; preserved');
const record = {at:new Date().toISOString(),ref,commit,tree,inputs,parent:prior.commit,head:git('rev-parse','HEAD'),changedInputs:changed,realIndexUnchanged:true,coverage:'Execution snapshot only; required new gates and runtime rebuild pending. No branch commit/push.'};
writeFileSync(path.join(out,'checkpoint-23.json'),JSON.stringify(record,null,2),{flag:'wx'});
console.log(JSON.stringify(record));
