import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import path from 'node:path';
const out=path.resolve('artifacts/beta-execution/20260930-landing-executor');
const prior=JSON.parse(readFileSync(path.join(out,'checkpoint-26.json'),'utf8'));
const actualIndex=execFileSync('git',['rev-parse','--git-path','index'],{encoding:'utf8'}).trim();
const hash=()=>createHash('sha256').update(readFileSync(actualIndex)).digest('hex');
const before=hash();
const index=path.join(mkdtempSync(path.resolve('artifacts/beta-execution/.profile/local-staging-20260930/cp27-index-')),'index');
const git=(...args)=>execFileSync('git',args,{encoding:'utf8',env:{...process.env,GIT_INDEX_FILE:index},stdio:['ignore','pipe','pipe']}).trim();
if(git('branch','--show-current')!=='design-v2'||git('rev-parse','refs/checkpoints/design-v2-closeout-26')!==prior.commit)throw new Error('Wrong candidate');
git('read-tree',prior.commit);
git('add','--',...Object.keys(prior.inputs),'docs/implementation/BETA_EXECUTION_STATUS.md','docs/implementation/OWNER_ACTIONS.md','artifacts/design-v2/BUGS.md','artifacts/design-v2/NOTES.md','artifacts/beta-execution/20260930-landing-executor/SCENARIO_REVIEW.md');
const tree=git('write-tree');
const inputs=Object.fromEntries(Object.keys(prior.inputs).map(p=>[p,git('rev-parse',tree+':'+p)]));
const ref='refs/checkpoints/design-v2-closeout-27';
const commit=git('commit-tree',tree,'-p',prior.commit,'-m','design-v2: broaden local scenarios and repair focus and reviewer-note handling');
git('update-ref',ref,commit,'0000000000000000000000000000000000000000');
if(hash()!==before)throw new Error('Real index changed; preserved');
const record={at:new Date().toISOString(),ref,commit,tree,parent:prior.commit,inputs,realIndexUnchanged:true,branchHead:git('rev-parse','HEAD'),coverage:'Frozen candidate; full sequential gate pending. No branch commit or push.'};
writeFileSync(path.join(out,'checkpoint-27.json'),JSON.stringify(record,null,2),{flag:'wx'});
console.log(JSON.stringify(record));
