import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {encryptSecretV2,decryptSecretV2,assertPlatformKeyRing,rewrapSecret} from './crypto.ts';
assert.match(process.version,/^v22\./);
const old=randomBytes(32).toString('base64');
process.env.FLOWLINE_ENCRYPTION_KEY=old;
process.env.FLOWLINE_PLATFORM_ENCRYPTION_KEY=randomBytes(32).toString('base64');
const context={table:'runtime_fixture',rowId:'synthetic-row',workspaceId:'synthetic-workspace',provider:'synthetic',purpose:'credential'};
const platform={...context,rowId:'platform-row',scope:'platform',workspaceId:'platform'};
const secret={token:randomBytes(24).toString('hex')};
const encrypted=encryptSecretV2(secret,context),admin=encryptSecretV2(secret,platform);
assert.deepEqual(decryptSecretV2(encrypted.ciphertext,encrypted.keyId,context),secret);
assert.deepEqual(decryptSecretV2(admin.ciphertext,admin.keyId,platform),secret);
assert.throws(()=>decryptSecretV2(encrypted.ciphertext,encrypted.keyId,{...context,workspaceId:'other'}));
assert.throws(()=>decryptSecretV2(admin.ciphertext,admin.keyId,context));
process.env.FLOWLINE_ENCRYPTION_KEY=randomBytes(32).toString('base64');
assert.throws(()=>decryptSecretV2(encrypted.ciphertext,encrypted.keyId,context));
process.env.FLOWLINE_ENCRYPTION_KEYS_OLD=old;
const rotated=rewrapSecret(encrypted.ciphertext,encrypted.keyId,context);
assert.deepEqual(decryptSecretV2(rotated.ciphertext,rotated.keyId,context),secret);
process.env.FLOWLINE_PLATFORM_ENCRYPTION_KEY=process.env.FLOWLINE_ENCRYPTION_KEY;
assert.throws(()=>assertPlatformKeyRing());
console.log(JSON.stringify({node:process.version,checks:7,status:'PASS_CRYPTO_ONLY'}));
